#cloud-config
# vim: syntax=yaml
#
# ***********************
# 	---- for more examples look at: ------
# ---> https://cloudinit.readthedocs.io/en/latest/topics/examples.html
# ******************************
#
# This is the configuration syntax that the write_files module
# will know how to understand. encoding can be given b64 or gzip or (gz+b64).
# The content will be decoded accordingly and then written to the path that is
# provided.
ssh_pwauth: true
disable_root: false
hostname: ${hostname}

users:
 - name: jose
   plain_text_passwd: linux
   lock_passwd: false
   shell: /bin/bash
   sudo: ALL=(ALL) NOPASSWD:ALL
   ssh_authorized_keys:
     - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDDNnLGuv5fNmFO0TdSYW4tcbnRphIa/s5NCT3+MZTtw3rHutBbSr91F/L0XU4L4Ig2r+vb65bawkNapkYNo0xaOkjlWEb9ci6u6u6AVbqSLbLB8FpiN6A8hwjopaHX9ag2myDcGBhF70zDC7ryqke2E3lV4m8WMpoueJPiQVmIURfHsYk4KzsBX0BcuBd3W3ZF5A+/p76lmBE66UaSAZCkG8gR48FA8d4wF/jI1Xnl1VObFA89h5LZ2G7tbDU/fNPYD0flB2hZIAnlr/f+td1fW0nnABftiLB0+lsfmsc+P0P3eTTxAZrhI3kW81TON57+KilqfrHa9RXv0eR4nvcGurkAJggP7ckrxSShZ5vbWWsp12MO4gPolCTJpLy+iJi9R4nLk5001wC0quglQRT6UN4grwuLQXyPBNcD5JXR261lObNFLpQSodvCcTcYEO2OAsE2aU/6pPkZ7Jb5c9GYijwcrc6wssKPGJLvjtAW4XYMlZIcRaecYnRMQ7OMFa+zBhQLSd/MLebFXkpC6F+2WrpT6mLTQyG7R7An0sNOXGQ1ERqbtLrZ/mXsQ7nZz61uLP9Kk7jnzc9YgIfPEd43LKo0AffB39Yl16PdqY2jtnSQyIOLyfp1J20+XfXjBv+oJX7fHmAyG6vDsqVxB/TikE+VthKdM/D3VKQhKddjmw== jose

mounts:
  - [ swap ]

write_files:
  # Enable IP Forward
  - path: /etc/sysctl.d/10-ip-forwarding.conf
    permissions: '0644'
    content: |
      net.ipv4.conf.all.forwarding=1
  - path: /etc/sysctl.d/99-kubernetes-cri.conf
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
      net.bridge.bridge-nf-call-ip6tables = 1
  - path: /etc/kubeadm-init.yaml
    permissions: '0644'
    content: |
      apiVersion: kubeadm.k8s.io/v1beta3
      kind: InitConfiguration
      skipPhases:
        - addon/kube-proxy
      bootstrapTokens:
        - groups:
            - system:bootstrappers:kubeadm:default-node-token
          token: abcdef.0123456789abcdef
          usages:
            - signing
            - authentication   
      localAPIEndpoint:
        bindPort: 6443   
      nodeRegistration:
        criSocket: unix:///var/run/crio/crio.sock
        imagePullPolicy: IfNotPresent
        name: ${hostname}
        taints:
          - key: "kubeadmNode"
            value: "someValue"
            effect: "NoSchedule"   
      ---
      apiVersion: kubeadm.k8s.io/v1beta3
      kind: ClusterConfiguration
      apiServer:
        timeoutForControlPlane: 4m0s      
      certificatesDir: /etc/kubernetes/pki
      clusterName: kubernetes
      controllerManager: {}
      dns: {}
      etcd:
        local:
          dataDir: /var/lib/etcd
      imageRepository: registry.k8s.io
      kubernetesVersion: 1.27.0
      networking:
        serviceSubnet: 10.50.0.0/16
        podSubnet: 10.60.0.0/16
        dnsDomain: cluster.local
      scheduler: {}

package_update: true

runcmd:
  - [ modprobe, br_netfilter]
  - [ sysctl, "--system"]
  - [ systemctl, enable, crio ]
  - [ systemctl, start, crio ]
  - [ kubeadm, config, images, pull ]
  - [ helm, repo, add, cilium, "https://helm.cilium.io/" ]
